// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:flutter_app/features/character/data/model/character_model.dart';
import 'package:flutter_app/features/character/data/model/submodels/character_location_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CharacterLocationAdapter());
    registerAdapter(CharacterModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CharacterLocationAdapter());
    registerAdapter(CharacterModelAdapter());
  }
}
